// <auto-generated />
using System;
using Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int").HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                    b.Property<DateTime>("DataCadastro").HasColumnType("datetime2");
                    b.Property<string>("CriadoPor").HasColumnType("varchar(20)");
                    b.Property<string>("UltimaModificacaoPor").HasColumnType("varchar(20)");
                    b.Property<DateTime?>("UltimaModificacao").HasColumnType("datetime2");
                    b.Property<string>("Nome").HasColumnType("varchar(250)");
                    b.Property<string>("CodigoDeBarras").HasColumnType("varchar(100)");
                    b.Property<string>("Descricao").HasColumnType("varchar(max)");
                    b.Property<decimal>("Preco").HasColumnType("decimal(18,6)");
                    b.Property<string>("Status").HasColumnType("varchar(1)");
                    b.HasKey("Id");
                    b.ToTable("TB_Produtos");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int").HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                    b.Property<DateTime>("DataCadastro").HasColumnType("datetime");
                    b.Property<DateTime>("DataNascimento").HasColumnType("datetime2");
                    b.Property<string>("Nome").HasColumnType("varchar(50)");
                    b.Property<string>("SobreNome").HasColumnType("varchar(20)");
                    b.Property<string>("Email").HasColumnType("varchar(50)");
                    b.Property<string>("Telefone").HasColumnType("varchar(20)");
                    b.Property<string>("Perfil").HasColumnType("varchar(20)");
                    b.Property<string>("Status").HasColumnType("varchar(1)");
                    b.HasKey("Id");
                    b.ToTable("TB_Usuario");
                });

            modelBuilder.Entity("Domain.Entities.UsuarioLogin", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int").HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                    b.Property<int>("IdUsuario").HasColumnType("int");
                    b.Property<DateTime>("DataCadastro").HasColumnType("datetime");
                    b.Property<string>("Email").HasColumnType("varchar(50)");
                    b.Property<string>("PasswordHash").HasColumnType("varchar(max)");
                    b.Property<string>("Status").HasColumnType("varchar(1)");
                    b.HasKey("Id");
                    b.ToTable("TB_Usuario_Login");
                });
#pragma warning restore 612, 618
        }
    }
}
